# -*- coding: utf-8 -*-
"""Coral (3D & 2D) Visualization Setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yY8hEkqaI7RU8w0yhAN_zGGyKPKJpHov
"""

import sys; sys.modules.pop('ipywidgets', None)
!pip install open3d plotly numpy | grep "Successfully installed" || echo "All packages already installed"

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

"""# 3D Model Segmentation

---
"""

import open3d as o3d
import plotly.graph_objects as go
import numpy as np

obj_path = '/content/drive/MyDrive/Coral AI/drive-download-20260309T231545Z-3-001/bouquet34-36.obj'
mesh = o3d.io.read_triangle_mesh(obj_path)
verts, faces, colors = np.asarray(mesh.vertices), np.asarray(mesh.triangles), np.asarray(mesh.vertex_colors)

fig = go.Figure(go.Mesh3d(x=verts[:,0], y=verts[:,1], z=verts[:,2], i=faces[:,0], j=faces[:,1], k=faces[:,2], vertexcolor=colors, hoverinfo='skip', flatshading=True))

fig.update_layout(
    scene=dict(
        xaxis_visible=False, yaxis_visible=False, zaxis_visible=False,
        aspectmode='data',
        camera_eye=dict(x=0.8, y=0.8, z=0.8)
    ),
    margin=dict(l=0, r=0, b=0, t=0),
    annotations=[dict(
        text="Drag to rotate<br>Pinch/Scroll to zoom<br>Right-click to pan<br>etc.",
        showarrow=False, xref="paper", yref="paper", x=0.05, y=0.95,
        xanchor="left", yanchor="top", font=dict(size=14, color="black"),
        bgcolor="rgba(255,255,255,0.5)", bordercolor="black", borderwidth=1, borderpad=4
    )]
)

fig.show(config={'displayModeBar': True})

import open3d as o3d
import plotly.graph_objects as go
import numpy as np
import os

folder_path = '/content/drive/MyDrive/Coral AI/drive-download-20260309T231545Z-3-001/'

def create_obj_plot(file_name, title, color_fallback):
    path = os.path.join(folder_path, file_name)
    if not os.path.exists(path):
        print(f"File not found: {file_name}")
        return None

    mesh = o3d.io.read_triangle_mesh(path)
    if not mesh.has_vertex_normals():
        mesh.compute_vertex_normals()

    verts = np.asarray(mesh.vertices)
    faces = np.asarray(mesh.triangles)

    # Attempt to get texture/vertex colors
    colors = np.asarray(mesh.vertex_colors) if mesh.has_vertex_colors() else None

    fig = go.Figure(go.Mesh3d(
        x=verts[:, 0], y=verts[:, 1], z=verts[:, 2],
        i=faces[:, 0], j=faces[:, 1], k=faces[:, 2],
        vertexcolor=colors if colors is not None else None,
        color=color_fallback if colors is None else None,
        flatshading=True
    ))

    fig.update_layout(
        title=title,
        scene=dict(aspectmode='data', xaxis_visible=False, yaxis_visible=False, zaxis_visible=False),
        margin=dict(l=0, r=0, b=0, t=40)
    )
    return fig

# Generate and show the two separate plots
fig1 = create_obj_plot("seaboard_Taitusi_1.obj", "Series 1 Visualization", "gray")
if fig1: fig1.show()

fig3 = create_obj_plot("seaboard_Taitusi_3.obj", "Series 3 Visualization", "gold")
if fig3: fig3.show()

import open3d as o3d
import plotly.graph_objects as go
import numpy as np
import os

# Define the path (using the same folder from your notebook)
folder_path = '/content/drive/MyDrive/Coral AI/drive-download-20260309T231545Z-3-001/'

# List of your STL files grouped by category
stl_files = {
    "Column 3": ["seaboard_Taitusi_3_C3_1.stl", "seaboard_Taitusi_3_C3_2.stl", "seaboard_Taitusi_3_C3_3.stl", "seaboard_Taitusi_3_C3_4.stl"],
    "Row 3": ["seaboard_Taitusi_3_R3_1.stl", "seaboard_Taitusi_3_R3_2.stl", "seaboard_Taitusi_3_R3_3.stl", "seaboard_Taitusi_3_R3_4.stl"],
    "Section 3": ["seaboard_Taitusi_3_S3_1.stl", "seaboard_Taitusi_3_S3_2.stl", "seaboard_Taitusi_3_S3_3.stl", "seaboard_Taitusi_3_S3_4.stl"]
}

# Colors for each group (RGB)
group_colors = {
    "Column 3": [0.1, 0.7, 0.1],  # Greenish
    "Row 3": [0.1, 0.1, 0.7],     # Bluish
    "Section 3": [0.7, 0.1, 0.1]  # Reddish
}

fig = go.Figure()

for group_name, files in stl_files.items():
    color = group_colors[group_name]
    for file_name in files:
        path = os.path.join(folder_path, file_name)

        if os.path.exists(path):
            # Load STL
            mesh = o3d.io.read_triangle_mesh(path)
            if not mesh.has_vertex_normals():
                mesh.compute_vertex_normals()

            verts = np.asarray(mesh.vertices)
            faces = np.asarray(mesh.triangles)

            # Add to Plotly figure
            fig.add_trace(go.Mesh3d(
                x=verts[:, 0], y=verts[:, 1], z=verts[:, 2],
                i=faces[:, 0], j=faces[:, 1], k=faces[:, 2],
                color=f'rgb({int(color[0]*255)}, {int(color[1]*255)}, {int(color[2]*255)})',
                name=file_name,
                opacity=0.6,
                showlegend=True
            ))
        else:
            print(f"File not found: {file_name}")

fig.update_layout(
    title="Seaboard Taitusi Series 3 - STL Visualization",
    scene=dict(aspectmode='data', xaxis_visible=False, yaxis_visible=False, zaxis_visible=False),
    margin=dict(l=0, r=0, b=0, t=40)
)

fig.show()

"""# 2D Flourescence Image Analysis

---


"""

import PIL.Image
import matplotlib.pyplot as plt
import os

folder_path = '/content/drive/MyDrive/Coral AI/drive-download-20260309T231545Z-3-001/'
file_names = ['C1 (T).JPG', 'C8 (T).JPG', 'SX-3.JPG', 'SX-5.JPG']

fig, axes = plt.subplots(1, 4, figsize=(20, 10))

for i, name in enumerate(file_names):
    img_path = os.path.join(folder_path, name)
    if os.path.exists(img_path):
        img = PIL.Image.open(img_path)
        axes[i].imshow(img)
        axes[i].set_title(name)
    else:
        axes[i].text(0.5, 0.5, f'File not found:\n{name}', ha='center', va='center')
    axes[i].axis('off')

plt.tight_layout()
plt.show()

import cv2
import numpy as np

fig, axes = plt.subplots(3, 4, figsize=(20, 12))

for i, name in enumerate(file_names):
    img_path = os.path.join(folder_path, name)

    if os.path.exists(img_path):
        # Load with OpenCV
        img_bgr = cv2.imread(img_path)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        # Convert to HSV
        hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)

        # Green mask (tune this later)
        lower_green = np.array([35, 20, 20])
        upper_green = np.array([95, 255, 255])
        mask = cv2.inRange(hsv, lower_green, upper_green)

        # Clean mask
        kernel = np.ones((5,5), np.uint8)
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

        # Overlay
        overlay = img_rgb.copy()
        overlay[mask > 0] = [0, 0, 255]
        blended = cv2.addWeighted(img_rgb, 0.7, overlay, 0.3, 0)

        # Plot
        axes[0, i].imshow(img_rgb)
        axes[0, i].set_title(f"{name}\nOriginal")

        axes[1, i].imshow(mask, cmap="gray")
        axes[1, i].set_title("Mask")

        axes[2, i].imshow(blended)
        axes[2, i].set_title("Overlay")

    else:
        axes[0, i].text(0.5, 0.5, f"Not found:\n{name}", ha='center')

    # Turn off all axes
    for row in range(3):
        axes[row, i].axis('off')

plt.tight_layout()
plt.show()

import PIL.Image
import matplotlib.pyplot as plt
import os
import cv2
import numpy as np

folder_path = '/content/drive/MyDrive/Coral AI/drive-download-20260309T231545Z-3-001/'
file_names = ['C1 (T).JPG', 'C8 (T).JPG', 'SX-3.JPG', 'SX-5.JPG']

fig, axes = plt.subplots(4, 4, figsize=(20, 16))

for i, name in enumerate(file_names):
    img_path = os.path.join(folder_path, name)

    if os.path.exists(img_path):
        # Load image
        img_bgr = cv2.imread(img_path)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        # Convert to grayscale
        gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        # Blur slightly to reduce noise
        gray_blur = cv2.GaussianBlur(gray, (5, 5), 0)

        # Threshold grayscale image
        # Try changing 140 to 120 or 160 depending on results
        _, mask = cv2.threshold(gray_blur, 140, 255, cv2.THRESH_BINARY)

        # Clean mask
        kernel = np.ones((3, 3), np.uint8)
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

        # Make overlay in blue
        overlay = img_rgb.copy()
        overlay[mask > 0] = [0, 0, 255]   # blue in RGB
        blended = cv2.addWeighted(img_rgb, 0.7, overlay, 0.3, 0)

        # Plot original
        axes[0, i].imshow(img_rgb)
        axes[0, i].set_title(f"{name}\nOriginal")
        axes[0, i].axis('off')

        # Plot grayscale
        axes[1, i].imshow(gray, cmap='gray')
        axes[1, i].set_title("Grayscale")
        axes[1, i].axis('off')

        # Plot mask
        axes[2, i].imshow(mask, cmap='gray')
        axes[2, i].set_title("Mask")
        axes[2, i].axis('off')

        # Plot overlay
        axes[3, i].imshow(blended)
        axes[3, i].set_title("Overlay")
        axes[3, i].axis('off')

    else:
        for row in range(4):
            axes[row, i].text(0.5, 0.5, f'File not found:\n{name}', ha='center', va='center')
            axes[row, i].axis('off')

plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

